name: flare_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_analytics: ^11.3.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/services/
